---
name: 'Semantic Release'
description: 'Runs Semantic Release in conv_cicda image'
inputs:
  dryrun:
    description: 'Run semantic release in dry run mode --dry-run'
    required: false
runs:
  using: 'docker'
  image: './Dockerfile'
  args:
    - ${{ inputs.dryrun }}
